safe: True
port: 4001
base-url:    /

gems:
  - jekyll-sitemap

source:      ./source/site
destination: ./_gh_pages
plugins:     ./source/site/_plugins

future:      true
lsi:         false
highlighter: true
permalink:   :title

rdiscount:
  extensions: []

# Custom vars
current_version:  0.1.2
site: https://gmachina.net
author: Unmodded.com
desc: gMachina is a first person, psychological horror adventure game, scheduled to be released on PC, Mac, and Linux.
